import { ExtendGlobalProps, registerCustomElement } from "ojs/ojvcomponent";
import { h, ComponentProps, ComponentType } from "preact";
//import componentStrings = require("ojL10n!./resources/nls/wallet-manager-strings");
import "css!dashboard/wallet-manager/wallet-manager-styles.css";
import { sc, rpc, tx, wallet as wallet2, u, CONST } from '@cityofzion/neon-core';
import { wallet as wallet3 } from '@cityofzion/neon-core-neo3';
import * as Logger  from 'ojs/ojlogger';
import axios from 'axios';
import { Signal, computed, effect, signal, useSignal, useSignalEffect } from "@preact/signals";
import "ojs/ojchart";
import "ojs/ojactioncard";
import "ojs/ojcolorspectrum";
import "ojs/ojlistview";
import "ojs/ojlistitemlayout";
import "ojs/ojinputtext";
import "ojs/ojbutton";
import "ojs/ojformlayout";
import "ojs/ojvalidationgroup";
import "ojs/ojpopup";
import "ojs/ojdrawerpopup";
import { DrawerPopupElement } from "ojs/ojdrawerpopup";
import { ojChart } from "ojs/ojchart";
import { ojColorSpectrum} from "ojs/ojcolorspectrum";
import { ojValidationGroup } from 'ojs/ojvalidationgroup';
import { InputTextElement } from "ojs/ojinputtext";
import { InputNumberElement } from "ojs/ojinputnumber";
import { ojListView } from "ojs/ojlistview";
//import { ArrayListDataProvider } from "ojs/ojarraydataprovider";
import { IntlNumberConverter } from "ojs/ojconverter-number";
import { KeySetImpl } from "@oracle/oraclejet/ojkeyset";
import { ojButton } from "ojs/ojbutton";
import BigNumber from "./bignumber"
import { BLACK } from "ojs/ojcolor";
import { WalletJSON } from "@cityofzion/neon-core/lib/wallet";
import { AssetCard } from "./asset-card";
//import ArrayDataProvider = require("ojs/ojarraydataprovider");
//import { AssetTransactions } from "./asset-transactions";
import { ojPopup } from "ojs/ojpopup";
import { Asset, AssetTransactionsMessage, CAsset, CWallet, KEY, addWalletToStorage, deleteWalletFromStorage, getN3AddressBalances, getN3AllTxs, getN3AssetTxs, getSelectedTagsFromStorage, loadWalletsFromStorage, updateWalletToStorage } from "./wallet-lib";
import { WalletList, refreshLastUpdatedTime } from "./wallet-list";
import { WChartData, WalletCharts } from "./wallet-charts";
import { WalletEditor } from "./wallet-editor";
import { prices, startPriceRefreshTimer, stopPriceRefreshTimer } from "dashboard/price-list/price-list";
import { createNotification } from "dashboard/notifications-layer/notifications-layer";
import * as Color from "ojs/ojcolor";
import { ojComboboxMany } from "ojs/ojselectcombobox";
import { AssetManager, showAssetManagerRoute } from "./asset-manager";
import transactionsDbService from "dashboard/flamingo-api/indexdb/transactionsDbService";


//const lvw = document.getElementById('lvWallets') as ojListView<{keyAttributes: "name"}, wallet3.Wallet[]>;
//const wcol = document.getElementById('wcol') as ojColorSpectrum;
//const wg = document.getElementById('wg') as InputNumberElement;
//const wn = document.getElementById('wn') as InputTextElement<string>;
//const wpk = document.getElementById('wpk') as InputTextElement<string>;
//const wk = document.getElementById('wk') as InputTextElement<string>;
//const tracker = document.getElementById('tracker') as ojValidationGroup;
//const baw = document.getElementById('butAddWallet') as ojButton;
console.log("form-elements > init");
export const bcrHidden = signal<boolean>(false);
export const buHidden = signal<boolean>(true);
export const bclrHidden = signal<boolean>(false);
export const bcloHidden = signal<boolean>(true);
export const brb = signal<boolean>(true);
//const we = document.getElementById('walletEditor') as HTMLElement;
//const wt = document.getElementById('wt') as ojComboboxMany<any, any, any>;
//const de = document.getElementById('de') as DrawerPopupElement;
//const dat = document.getElementById('dat') as DrawerPopupElement;