import { Signal, computed, effect, signal, useSignal, useSignalEffect } from "@preact/signals";

console.log("form-elements > init");
//const lvw = document.getElementById('lvWallets') as ojListView<{keyAttributes: "name"}, wallet3.Wallet[]>;
//const wcol = document.getElementById('wcol') as ojColorSpectrum;
//const wg = document.getElementById('wg') as InputNumberElement;
//const wn = document.getElementById('wn') as InputTextElement<string>;
//const wpk = document.getElementById('wpk') as InputTextElement<string>;
//const wk = document.getElementById('wk') as InputTextElement<string>;
//const tracker = document.getElementById('tracker') as ojValidationGroup;
export const bawHidden = signal<boolean>(false);
export const bcrHidden = signal<boolean>(false);
export const buHidden = signal<boolean>(true);
export const bclrHidden = signal<boolean>(false);
export const bcloHidden = signal<boolean>(true);
export const brbHidden = signal<boolean>(true);
export const tbnDisabled = signal<boolean>(false);
//const we = document.getElementById('walletEditor') as HTMLElement;
//const wt = document.getElementById('wt') as ojComboboxMany<any, any, any>;
//const de = document.getElementById('de') as DrawerPopupElement;
//const dat = document.getElementById('dat') as DrawerPopupElement;